feat: Support serializing and deserializing LoRA adapters
coreweave/vllm pull request #3
Opened 2024-12-09 21:09 UTC by sangstar

# Serializing and deserializing LoRA adapters using `tensorizer`
This PR allows LoRA adapters to be serialized and deserialized using `tensorizer`. A test is added to confirm this and serializing LoRA files can be done with the same script that can save vLLM models in `examples/tensorize_vllm_model.py`.

## Summary of changes

- Adjusted the CLI args for `.buildkite/test-pipeline.yaml`'s invocation of the `tensorize_vllm_model.py` example script to additionally save and load a LoRA adapter, testing a model generation after deserialization to confirm the LoRA adapter was loaded properly
- Added `--lora-path` to `tensorize_vllm_model.py` as a base argparser argument that allows a user to specify the HuggingFace reference ID for a LoRA adapter, which can be either serialized or deserialized depending on whether the `serialize` or `deserialize` subparser is indicated.
- Added `test_serialize_and_deserialize_lora` to `test_tensorizer.py` testing saving and loading LoRA adapters with `tensorizer`.
- Allows deserializing a LoRA adapter by allowing `TensorizerConfig` to be passed in as a kwarg to `LoRARequest`. When this is done, the LoRA tensors are assumed to be in `tensorizer` format and deserialized according to the parameters given in the `TensorizerConfig` provided.

2025-02-18 16:39 UTC, Rexwang8 approved these changes
Looks good! Tests pass, code looks fine. Good job!!

2025-02-18 16:39 UTC, Rexwang8 commented on .buildkite/test-pipeline.yaml
> +    - python3 tensorize_vllm_model.py --model meta-llama/Llama-2-7b-hf --lora-path yard1/llama-2-7b-sql-lora-test serialize --serialized-directory /tmp/ --suffix v1 && python3 tensorize_vllm_model.py
Can you explain the reasoning behind changing the model here?

2025-02-18 16:39 UTC, Rexwang8 commented on vllm/lora/models.py
> +                              lora_dir: str,
It looks like the formatting here is changed from the base?

2025-02-20 08:09 UTC, Eta0 requested changes

2025-02-20 08:09 UTC, Eta0 commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +    cleanup()
A better pattern for this is usually to use `try` + `finally`, but in this case, `tempfile.TemporaryDirectory` is a context manager, so you can achieve the same effect with a `with` statement:
```suggestion
def tmp_dir():
    with tempfile.TemporaryDirectory() as path:
        yield path
```
(Note: this yields the equivalent of just `tmp_dir.name` as a `str` instead of the full stateful object)

2025-02-20 08:09 UTC, Eta0 commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +    model_uri = tmp_dir.name + "/model.tensors"
You repeatedly use `tmp_dir` only to use it in the expression `tmp_dir.name + "/model.tensors"`, so it seems like it would make more sense to have another fixture that returns this string directly.

2025-02-20 08:09 UTC, Eta0 commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +    args = EngineArgs(model=MODEL_NAME, )
Extraneous comma and space.
```suggestion
    args = EngineArgs(model=MODEL_NAME)
```

2025-02-20 08:09 UTC, Eta0 commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +    ]
You should split these strings up instead of disabling the inspection here.

2025-02-20 08:09 UTC, Eta0 commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +        completion_tokens=5, prompt_tokens=6, total_tokens=11)
Is it valid to have any other potential finish reasons occur here?

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/models.py
> +                **tensorizer_args.deserializer_params)
Tensorizer's default is to use `torch.device("cuda")` if CUDA is available (and `torch.device("cpu")` otherwise), which will generally correspond to the same device as `cuda:{torch.cuda.current_device()}` unless you expect the contextual current device to change for some reason in the middle of reading the tensors. In other words, you shouldn't have to specify this here.
```suggestion
            tensors = TensorDeserializer(
                lora_tensor_path,
                dtype=tensorizer_config.dtype,
                **tensorizer_args.deserializer_params)
```

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/models.py
> +                        f"is correct")
Not sure why this was changed
```suggestion
                        f" Please verify that the loaded LoRA module is correct"
                    )
```

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/models.py
> +        tensorizer_config = kwargs.get("tensorizer_config")
Why is this using `kwargs` instead of an argument with a default value? Adding `kwargs` to a function is significant since it will start silently accepting and ignoring incorrect parameter names passed to the function if you don't also go out of your way to check for extraneous entries in it. Is there a reason you need to use `**kwargs` over `tensorizer_config=None`?

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/peft_helper.py
> +        tensorizer_config = kwargs.get("tensorizer_config")
Same comment about adding `kwargs`. Can this be replaced with a normal parameter with a default value?

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/peft_helper.py
> +                             **tensorizer_args.stream_params) as f:
It seems misleading that a method named `from_local_dir` is explicitly given the opportunity here to load something from the network rather than from a local dir.

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/worker_manager.py
> +                                          None))
You defined the `LoRARequest` class to have a default value of `None` for `lora_request.tensorizer_config`. Is there a reason (e.g. metaclass witchcraft) the attribute might not be defined here in spite of that that motivated using `getattr`?

2025-02-20 08:09 UTC, Eta0 commented on vllm/model_executor/model_loader/tensorizer.py
> +from huggingface_hub import snapshot_download
If this package wasn't directly imported before in this codebase until this change, make sure it's accounted for in a requirements.txt file somewhere (even if it's already indirectly required as a dependency of another package).

2025-02-20 08:09 UTC, Eta0 commented on vllm/model_executor/model_loader/tensorizer.py
> +        self.tensorizer_dir = self.tensorizer_uri.rpartition("/")[0]
You can use `os.path.dirname` if that is what you intend to capture here

2025-02-20 08:09 UTC, Eta0 commented on vllm/model_executor/model_loader/tensorizer.py
> +from safetensors.torch import load_file
IMO this should be imported as `import safetensors.torch` and referenced later as `safetensors.torch.load_file`, because seeing it invoked as a function simply named `load_file()` later on looks very vague, whereas seeing it invoked as `safetensors.torch.load_file()` would give more useful context.

2025-02-20 08:09 UTC, Eta0 commented on vllm/model_executor/model_loader/tensorizer.py
> +    config_path = os.path.join(lora_files, "adapter_config.json")
If this is something that could be subject to change, instead of commenting this here, you could refactor `vllm.lora.models.LoRAModel.from_local_checkpoint` so that it uses a helper function to retrieve these paths, and then use the same helper function here. This would make the link between the two usages more clear (e.g. an IDE could tell someone looking at it that it's used in multiple places, or if it's edited in a way that makes it incompatible, the test suite here will more likely raise a red flag).

As pseudocode:
```python
# In vllm.lora.models

def lora_file_paths(lora_dir_path):
    # Instantiate a dataclass, namedtuple, etc. with all the assumed filenames
    foo_path = os.path.join(...)
    bar_path = os.path.join(...)
    # ...Others...
    return ...

def from_local_checkpoint(lora_dir, ...):
    lora_files = lora_file_paths(lora_dir)  # Instead of a bunch of os.path.join calls
    # Then the rest of the loading logic


# Here, in vllm.model_executor.model_loader.tensorizer

from vllm.lora.models import lora_file_paths

def tensorize_lora_adapter(...):
    lora_dir = ...
    lora_files = lora_file_paths(lora_dir)
    # Then the rest of the serialization logic
```

On the other hand, if these names are set in stone and have reason they probably will not change, then don't worry about it.

2025-02-20 08:09 UTC, Eta0 commented on vllm/model_executor/model_loader/tensorizer.py
> +                f"/adapter_model.tensors")
As the dual to the preceding comment, these paths should also ideally be defined in a helper function so that the deserialization logic can share them without implicitly relying on using the same copy-pasted, hardcoded names.

2025-02-20 08:09 UTC, Eta0 commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +                                              tensorizer_uri=model_uri)))
What does this test? It feels like this function has an elaborately-crafted prompt setup but doesn't end up using it for anything specific other than seeing if it runs without raising an exception.

Is the extent of this test case just checking that these functions can be called without runtime errors? If so, I'd simplify the prompt a bit, and use a less-intense model to test with. Let me know if there's more nuance here I'm not seeing, though. I'm not 100% on how this feature works.

2025-02-20 08:09 UTC, Eta0 commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +LORA_PATH = "yard1/llama-2-7b-sql-lora-test"
`meta-llama/Llama-2-7b-hf` as distributed on Hugging Face is a gated-access model that generally requires a token with special approval. Is that still the case in the way it is used here? Is there another model that could be used for testing that is not as complicated to access?

And, additionally, is it necessary to use a 7B model here? There are many benefits to keeping test cases lightweight (e.g. making it easier to run them on CI machines with limited compute resources, getting the test suite to finish faster, and so on). If this can be replaced with a smaller model without invalidating the tests, that would likely be less of a burden for project maintenance long-term.

2025-02-20 08:09 UTC, Eta0 commented on examples/other/tensorize_vllm_model.py
> +        from vllm.lora.request import LoRARequest
Do these need to be local, conditional imports? Unless importing a module has a substantial performance cost or requires extra dependencies that may not be met, it would be better to put them at the top of the module in the usual block of imports.

The import from `vllm` is definitely safe to make unconditional; there is even already another `from vllm import ...` statement at the top of the file, so this will definitely not have any overhead or extra requirements.

2025-02-20 08:09 UTC, Eta0 commented on examples/other/tensorize_vllm_model.py
> +        "LoRARequest with type TensorizerConfig."
The note about deserialization is somewhat hard to understand. It may be helpful to refer to example code or documentation here.

If nothing else, some more information on usage or a brief example could be included in the argument parser description or [epilog](https://docs.python.org/3/library/argparse.htl#epilog), though in general that is not the most accessible spot to sequester useful information.

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/models.py
> +                              **kwargs) -> "LoRAModel":
Update the docstring to reflect any added parameters.

2025-02-20 08:09 UTC, Eta0 commented on vllm/lora/request.py
> +    tensorizer_config: Optional["TensorizerConfig"] = None
Document the usage of this somewhere, e.g. the docstring for this class.

2025-02-20 08:09 UTC, Eta0 commented on .buildkite/test-pipeline.yaml
> +    - python3 other/tensorize_vllm_model.py --model meta-llama/Llama-2-7b-hf --lora-path yard1/llama-2-7b-sql-lora-test serialize --serialized-directory /tmp/ --suffix v1 && python3 other/tensorize_v
It's very plausible that a CI pipeline would not have the requisite permissions to access a gated `meta-llama` model. As mentioned in another comment, the choice of model here should be reconsidered for access and for size.

2025-02-20 16:31 UTC, sangstar reviewed
Just meant to respond to review comments; this is not intended as a review on my part. >.<

2025-02-20 16:31 UTC, sangstar commented on .buildkite/test-pipeline.yaml
> +    - python3 other/tensorize_vllm_model.py --model meta-llama/Llama-2-7b-hf --lora-path yard1/llama-2-7b-sql-lora-test serialize --serialized-directory /tmp/ --suffix v1 && python3 other/tensorize_v
Good point. The choice of model here wasn't arbitrary, but rather due to the fact that any test that vLLM runs that tests its LoRA machinery invariably uses the `yard1/llama-2-7b-sql-lora-test` LoRA adapter for `meta-llama/Llama-2-7b-hf`. vLLM's CI suite has a token authenticated to download Llama 2 weights and Llama 2 is used frequently for vLLM's tests ([an example for a LoRA test explicitly](https://github.com/vllm-project/vllm/blob/main/tests/lora/test_add_lora.py)), so the runners are capable of loading it without any OOM issues. I felt there was no reason to break from the conventional choice of LoRA adapter and model here, and would give the developers greater confidence for the integration if it's working for their chosen adapter.

2025-02-20 16:31 UTC, sangstar commented on examples/other/tensorize_vllm_model.py
> +        from vllm.lora.request import LoRARequest
There's no need for conditional imports here. I'll put these at the top.

2025-02-20 16:31 UTC, sangstar commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +LORA_PATH = "yard1/llama-2-7b-sql-lora-test"
Like I mentioned in a previous comment, vLLM's CI runners have an access token authenticated to download Llama 2, and is loaded fairly often in their testing suite, so I figured it was reasonable to hold them to being able to handle this.

That said, the point of this test script was to make sure we add a tensorizer test script to their fast check tests, so it might be a good idea to prioritize a smaller model size and possibly try to find a different LoRA adapter, because they may not like a model size this large having to be loaded for their fast check tests, unless this is already being done, so I take your point and think I need to make sure this is absolutely necessary.

2025-02-20 16:31 UTC, sangstar commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +    args = EngineArgs(model=MODEL_NAME, )
Thanks for the catch. I wonder why the linters never spotted this?

2025-02-20 16:31 UTC, sangstar commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +    cleanup()
I guess `try + finally` is pretty functionally equivalent to a context manager due to having a guaranteed cleanup?

2025-02-20 16:31 UTC, sangstar commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +        completion_tokens=5, prompt_tokens=6, total_tokens=11)
There wasn't much thought put in to this, frankly. It's reused the same couple lines of code from `test_single_completion` from `test_completion.py` and `test_encoder_decoder.py`, so I deferred to those scripts to justify the correctness of those particular couple of assertions.

2025-02-20 16:31 UTC, sangstar commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +    ]
[This was directly scraped from the LoRA tests.](https://github.com/vllm-project/vllm/blob/ed6e9075d31e32c8548b480a47d1ffb77da1f54c/tests/lora/test_llama_tp.py#L35-L42)

Happy to adjust this, unless there's any risk of it being perceived as stuffy of me to try to use their test prompts but pretty it up, but surely that's overthinking.

2025-02-20 16:31 UTC, sangstar commented on tests/entrypoints/openai/test_tensorizer_entrypoint.py
> +                                              tensorizer_uri=model_uri)))
The LoRA adapter is only actually loaded in to the model when the `.generate` method is called for an `LLM` with a `lora_request: LoRARequest` kwarg, and yes, it's to try to make sure no exceptions are raised. Since this is the testing script I'm asking to be included in to their fast checks (which are always ran), I thought it would be more desirable for the developers to sequester more fine-grained unit tests in the dedicated `tests/tensorizer_loader.py` tests and have these tests just ensure end-to-end use doesn't result in any exceptions.

It was sort of inspired by other tests that are included in the fast check suite, such as `test_basic_correctness.py`, which are almost entirely void of any `assert` statements and just make sure end-to-end API stuff works.

2025-02-20 16:31 UTC, sangstar commented on vllm/lora/models.py
> +        tensorizer_config = kwargs.get("tensorizer_config")
The motivation was to along the lines of "I want to include my tensorizer hook, but I don't want to be as intrusive as to ask the developers to include my `tensorizer_config` as directly as an acknowledged parameter in their LoRA API with a docstring and everything. I'll instead only be intrusive enough as to ask them to allow `**kwargs`, setting a precedent for others to hook in their own stuff unintrusively.".

This has made me see though that this is the opposite of unintrusive; it's harming the API itself to allow `**kwargs` like this and making the LoRA machinery harder to maintain and setting a precedent of LoRA logic having to handle any number of random, undocumented parameters. I'll explicitly introduce `tensorizer_config` as a parameter.

2025-02-20 16:31 UTC, sangstar commented on vllm/lora/models.py
> +                        f"is correct")
Not sure either.

2025-02-20 16:31 UTC, sangstar commented on vllm/lora/peft_helper.py
> +        tensorizer_config = kwargs.get("tensorizer_config")
Yes. Will do.

2025-02-20 16:31 UTC, sangstar commented on vllm/lora/peft_helper.py
> +                             **tensorizer_args.stream_params) as f:
I agree that it's misleading. It was, however, the most logical place to inject hooks for loading with tensorizer. I think the code is where it should be if I ignore the name of the function, as functionally it's proven to be appropriately placed (as this is the official "config loading" piece, albeit meant to be local). I'm not really sure what to do about this that would make sense. I don't think renaming the class method would be appropriate, and I don't think this code should be anywhere else. Interested to hear your thoughts on this.

2025-02-20 16:31 UTC, sangstar commented on vllm/lora/worker_manager.py
> +                                          None))
I'm a bit hazy on my justification for this. I think initially I didn't give it a default value of `None`, but something about not doing this seemed to cause it to infer its type weirdly or something (some `msgspec.Struct` weirdness or something maybe). I can take a second look, but once it was happy when I made `None` its default value I mostly shrugged and carried on.

2025-02-20 16:31 UTC, sangstar commented on vllm/model_executor/model_loader/tensorizer.py
> +from huggingface_hub import snapshot_download
`huggingface_hub` is directly imported fairly frequently in the codebase.

2025-02-20 16:31 UTC, sangstar commented on vllm/model_executor/model_loader/tensorizer.py
> +    config_path = os.path.join(lora_files, "adapter_config.json")
`adapter_model.bin`, `adapter_model.safetensors` and `adapter_config.json` are all values that are set in stone, yep. LoRA adapters on HF Hub have that naming convention.

2025-02-20 16:31 UTC, sangstar commented on vllm/model_executor/model_loader/tensorizer.py
> +                f"/adapter_model.tensors")
Given that LoRA adapter model artifact filenames either start with `adapter_model.*` or `adapter_config.json`, I felt it would be fine to just hard-code and force filenames for serialized `adapter_model.safetensors` files to be `adapter_model.tensors`.

2025-05-09 23:13 UTC, wbrown approved these changes

2025-05-27 19:31 UTC, closed without merging